[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
exclude = '/nebari/template/'

[tool.setuptools_scm]
write_to = "nebari/_version.py"
version_scheme = "release-branch-semver"
local_scheme = "node-and-timestamp"
